name: binder-ovito-lammps

channels:
    - https://conda.ovito.org
    - conda-forge
    - nodefaults

dependencies:
    - ovito 
    - lammps
    - jupyterlab
    - mpi
    - numpy 
    - matplotlib
    - ipywidgets
    - pandas
